/* tslint:disable:max-line-length */
import { IStartViewTranslations } from '@/locale/interfaces'

const en: IStartViewTranslations = {
  $adultCount: 'adults',
  $baseData: 'Personal information',
  $baseDataSummary: `The climate diet – developed by the Finnish Environmental Institute (Syke) – helps you find out your carbon footprint and how to make it smaller.`,
  $birthDecade: 'The decade of birth',
  $childCount: 'children',
  $continueToCalculator: 'continue',
  $continueToCalculatorWithRegistration: 'login and continue',
  $familySize: 'Family size or number of housemates ',
  $familySizeDetails:
    'Family size or the number of housemates: The total housing footprint is divided by the number of people sharing the place.',
  $gender: 'Gender',
  $genderFemale: 'Female',
  $genderMale: 'Male',
  $genderOther: 'Other',
  $groupCode: 'Group code',
  $groupCodeDetails:
    'If you are part of a group doing Climate Diet together, insert the code given to you by the group leader here',
  $groupCodeError:
    'Group code verification failed. It is either expired or does not exist. Check the code and try again.',
  $infoForUsers:
    'The carbon footprint coefficients of housing, food and consumption have been updated with the newest research data. The results generated by the old calculation model are no longer available as averages of the results, but for logged in users their own result history will remain available for browsing. See what has changed in the ',
  $postalCode: 'Postal code',
  $postalCodeDetails:
    'The postal code is used in estimating energy consumption and regional comparisons. Postal codes in Finland consist of five numbers.',
  $yearlyIncome: 'Personal income before taxes',
  $siteSlogan: 'Calculate your carbon footprint and start a climate diet!',
  $registrationInfo:
    'Login each time you use the calculator to automatically store your results. Login is done via email and a single-use code, no passwords required. You can see your result history in the "Results" tab.',
  $termsOfUseInfo: 'Before continuing, familiarize yourself with the ',
  $changelog: 'change log',
}

export default en
